name: run
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Run rules
        run: |
          wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf -nv -O ./accelerated-domains.china.txt
          wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf -nv -O ./apple.china.txt
          wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf -nv -O ./google.china.txt
          cat ./accelerated-domains.china.txt ./apple.china.txt ./google.china.txt | sort | uniq > ./clash/chinalist.txt
          sed -i 's/server=\// - DOMAIN-SUFFIX,/g;s/\/114.114.114.114//g' ./clash/chinalist.txt
          sed -i '1s/^/payload:\n/' ./clash/chinalist.txt
          cat ./accelerated-domains.china.txt ./apple.china.txt ./google.china.txt | sort | uniq > ./shadowrocket/chinalist.txt
          sed -i 's/server=\//DOMAIN-SUFFIX,/g;s/\/114.114.114.114//g' ./shadowrocket/chinalist.txt
          rm ./accelerated-domains.china.txt ./apple.china.txt ./google.china.txt
      - name: Commit file
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
